spring:
  data:
    mongodb:
      username: admin
      password: admin
      host: localhost
      port: 27017
      database: product-service
      authentication-database: admin
  application:
    name: product-service
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs