services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: inventory_service
    ports:
      - "3306:3306"