services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-service-mysql
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: inventory_service
    ports:
      - "3316:3306"